import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadCore } from "./load-core.mjs";
import { planWrites } from "../scripts/apply-theme.mjs";

const rootDir = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => fs.readFileSync(path.join(rootDir, ...rel.split("/")), "utf8");
const voiceDir = path.join(rootDir, "assets", "voice", "ja");
const presenter = read("assets/dsh-whale-moe.js");
const client = read("lib/client.js");
const host = read("lib/index.js");

/* The pack is generated by scripts/voice-pack.py; when a clone has not built it
   the runtime simply stays silent. These checks only run on a built checkout. */
const packBuilt = fs.existsSync(path.join(voiceDir, "manifest.json"));
const manifest = packBuilt ? JSON.parse(read("assets/voice/ja/manifest.json")) : null;

function coreLines() {
  const core = loadCore();
  const lines = [];
  for (const bank of Object.values(core.LINES)) for (const line of bank) lines.push(line);
  for (const group of Object.values(core.DIALOGUE)) {
    for (const bank of Object.values(group)) for (const line of bank) lines.push(line);
  }
  return lines;
}

/* Bubble texts the presenter writes itself instead of picking from a core bank:
   every literal it hands to playVoiceFor() must be in the pack too. */
function presenterLiterals_() {
  return [...new Set([...presenter.matchAll(/playVoiceFor\("([^"]+)"\)/g)].map((match) => match[1]))];
}

test("every voiced line has a clip, and no clip is orphaned", { skip: !packBuilt }, () => {
  const lines = coreLines();
  const presenterLiterals = presenterLiterals_();
  const keys = Object.keys(manifest.files);
  assert.equal(
    keys.length,
    lines.length + presenterLiterals.length,
    "the manifest must cover every core line plus the presenter's fixed strings"
  );
  assert.equal(manifest.count, keys.length);
  assert.equal(new Set(lines).size, lines.length, "core lines are unique, so the map is unambiguous");

  const missing = lines.filter((line) => !manifest.files[line]);
  assert.deepEqual(missing.slice(0, 5), [], `${missing.length} core lines have no clip`);
  const missingLiterals = presenterLiterals.filter((line) => !manifest.files[line]);
  assert.deepEqual(missingLiterals, [], `presenter lines with no clip: ${missingLiterals.join(" | ")}`);

  const expected = new Set([...lines, ...presenterLiterals]);
  const unexpected = keys.filter((key) => !expected.has(key));
  assert.deepEqual(unexpected.slice(0, 5), [], `${unexpected.length} manifest keys match no line in the source`);

  const referenced = new Set(Object.values(manifest.files));
  const onDisk = fs.readdirSync(path.join(voiceDir, manifest.voice)).filter((name) => name.endsWith(".ogg"));
  const orphans = onDisk.filter((name) => !referenced.has(`${manifest.voice}/${name}`));
  assert.deepEqual(orphans.slice(0, 5), [], `${orphans.length} clip files are not referenced by the manifest`);
  assert.equal(onDisk.length, keys.length);
});

test("every clip is a readable Ogg file inside the voice directory", { skip: !packBuilt }, () => {
  const entries = Object.entries(manifest.files);
  for (const [line, rel] of entries) {
    assert.ok(!rel.includes("..") && !rel.startsWith("/"), `unsafe path for ${JSON.stringify(line)}: ${rel}`);
    const file = path.join(voiceDir, ...rel.split("/"));
    const stat = fs.statSync(file);
    assert.ok(stat.size > 2000, `${rel} is suspiciously small (${stat.size} bytes)`);
    assert.equal(fs.readFileSync(file).subarray(0, 4).toString("latin1"), "OggS", `${rel} is not an Ogg stream`);
  }
});

test("the presenter resolves a clip URL from the manifest and rejects unsafe values", () => {
  const start = presenter.indexOf("function voiceSourceFor(");
  const end = presenter.indexOf("\n  function ", start + 10);
  assert.ok(start > 0 && end > start, "voiceSourceFor must exist");
  const voiceSourceFor = new Function(`return (${presenter.slice(start, end).trim()});`)();

  const manifestFor = { files: { "Master~ what shall we do today?": "jf_tebukuro/01-lines-idle-i0.ogg" } };
  assert.equal(
    voiceSourceFor("Master~ what shall we do today?", manifestFor, "/assets/voice/ja/"),
    "/assets/voice/ja/jf_tebukuro/01-lines-idle-i0.ogg"
  );
  assert.equal(voiceSourceFor("not a line", manifestFor, "/assets/voice/ja/"), "");
  assert.equal(voiceSourceFor("cfg", { files: { cfg: "../../../etc/passwd" } }, "/v/"), "");
  assert.equal(voiceSourceFor("cfg", { files: { cfg: "/abs/path.ogg" } }, "/v/"), "");
  assert.equal(voiceSourceFor("cfg", null, "/v/"), "");
  assert.equal(voiceSourceFor(undefined, manifestFor, "/v/"), "");
});

test("the presenter speaks only what it shows, and defers uncovered lines to MiMo TTS", () => {
  assert.match(presenter, /var VOICE_ROOT = "\/assets\/voice\/ja\/";/);
  assert.match(presenter, /\{ key: "voiceJa", label: "Voice \(JP clips\)" \}/);
  /* the showLine() funnel */
  assert.match(
    presenter,
    /function showLineNow\(line\)[\s\S]*?var localized = localizeLine\(line\);[\s\S]*?playVoiceFor\(line\);[\s\S]*?typeBubble\(text, localized\)/
  );
  /* the reconcile loop writes two bubbles directly and used to be silent: the
     state line (the most-seen bubble) and the celebration override */
  assert.match(presenter, /playVoiceFor\(computed\.line\);\s*\n\s*typeBubble\(bubbleText, localizeLine\(computed\.line\)\);/);
  assert.match(presenter, /playVoiceFor\("Ehehe~ I like Master best!"\);/);
  /* a clip and the optional TTS bridge never both speak the same line */
  assert.match(presenter, /function showInteractionLine\(line\)[\s\S]*?showLine\(line\);[\s\S]*?if \(!lineHasVoice\(line\)\) emitInteractionLine\(localizeLine\(line\)\)/);
  assert.match(presenter, /function voiceEnabled\(\)[\s\S]*?return readPref\("voiceJa"\) && readPref\("chat"\);/);
  /* names no longer mute anything: 74% of clips contain one, so muting looked
     like a broken feature rather than a naming choice */
  assert.doesNotMatch(presenter, /if \(localized === String\(line\)\) playVoiceFor\(line\)/);
  /* autoplay refusals must not spam, and a gesture re-arms playback */
  assert.match(presenter, /started && typeof started\.catch === "function"[\s\S]*?voiceBlocked = true/);
  assert.match(presenter, /function onUserActivity\(\)[\s\S]*?if \(voiceBlocked\) voiceBlocked = false;/);
  assert.match(presenter, /if \(voiceEnabled\(\)\) loadVoiceManifest\(\);/);
});

test("silent bubbles can be explained from the console", () => {
  /* window.__dshWhaleVoice.misses[].reason names the exact cause */
  assert.match(presenter, /root\.__dshWhaleVoice = \{/);
  for (const reason of [
    "voice-off",
    "bubbles-off",
    "manifest-not-loaded",
    "not-in-pack",
    "autoplay-blocked",
    "autoplay-refused",
    "playback-error"
  ]) {
    assert.ok(presenter.includes(`"${reason}"`), `noteVoiceMiss must record ${reason}`);
  }
  assert.match(presenter, /VOICE_MISS_MAX = 20/, "the miss log stays bounded");
});

test("bundle mode serves the voice through the plugin asset route", () => {
  assert.match(
    client,
    /\.replace\('var VOICE_ROOT = "\/assets\/voice\/ja\/";', 'var VOICE_ROOT = "' \+ BASE \+ 'voice\/ja\/";'\)/
  );
  assert.match(client, /prefKey: "voiceJa"/);
  assert.match(host, /"\.ogg": "audio\/ogg"/);
});

test("the rewritten bundle URLs resolve to files the host route can serve", { skip: !packBuilt }, () => {
  /* client.js turns VOICE_ROOT into "<BASE>voice/ja/" where
     BASE = "/api/dsh-whale-musume/assets?f=". Reproduce that composition and
     check the host route's own parsing (strip the ?v= tail, resolve inside
     assets/) lands on a real file: a naming or root mismatch fails here. */
  const assetsDir = path.join(rootDir, "assets");
  const bundleRoot = "/api/dsh-whale-musume/assets?f=voice/ja/";
  const requested = new Set();

  const manifestUrl = bundleRoot + "manifest.json" + "?v=1";
  requested.add(new URL(manifestUrl, "http://127.0.0.1").searchParams.get("f").split("?")[0]);

  const [sampleLine] = Object.keys(manifest.files);
  const start = presenter.indexOf("function voiceSourceFor(");
  const end = presenter.indexOf("\n  function ", start + 10);
  const voiceSourceFor = new Function(`return (${presenter.slice(start, end).trim()});`)();
  const clipUrl = voiceSourceFor(sampleLine, manifest, bundleRoot);
  assert.ok(clipUrl.startsWith(bundleRoot), clipUrl);
  assert.equal(
    voiceSourceFor("bogus", { files: { bogus: "x.ogg" } }, bundleRoot).startsWith(bundleRoot),
    true,
    "the root rewrite applies to every clip"
  );
  requested.add(new URL(clipUrl, "http://127.0.0.1").searchParams.get("f").split("?")[0]);

  for (const rel of requested) {
    const target = path.normalize(path.join(assetsDir, rel));
    assert.ok(target.startsWith(assetsDir + path.sep), `${rel} escapes the assets directory`);
    assert.ok(fs.existsSync(target), `the host route would 404 on ${rel}`);
  }
});

/* The behavioural tests share one harness: playVoiceFor() closes over two other
   module-scope helpers, so both must be injected alongside it or the extracted
   copy throws a ReferenceError instead of exercising the code. */
function extractFunctionBody(name) {
  const start = presenter.indexOf(`function ${name}(`);
  const end = presenter.indexOf("\n  function ", start + 10);
  assert.ok(start > 0 && end > start, `${name} must exist`);
  return presenter.slice(start, end).trim();
}

function makeVoiceHarness(options = {}) {
  const plays = [];
  const audios = [];
  const misses = [];
  class FakeAudio {
    constructor() {
      this.src = "";
      this.currentTime = 0;
      audios.push(this);
    }
    play() {
      plays.push(this.src);
      if (options.throws) throw Object.assign(new Error("blocked"), { name: "NotAllowedError" });
      if (options.aborts) {
        return Promise.reject(
          Object.assign(new Error("The play() request was interrupted by a new load request."), { name: "AbortError" })
        );
      }
      if (options.refuses) {
        return Promise.reject(
          Object.assign(new Error("play() failed because the user didn't interact with the document first"), {
            name: "NotAllowedError"
          })
        );
      }
      return Promise.resolve();
    }
  }
  const factory = new Function(
    "readPref", "voiceSourceFor", "voiceManifest", "VOICE_ROOT", "root", "noteVoiceMiss", "loadVoiceManifest",
    `let voiceAudio = null;
     let voiceBlocked = false;
     ${extractFunctionBody("voiceBlockedReason")}
     ${extractFunctionBody("playVoiceFor")}
     return {
       play: playVoiceFor,
       blocked: function () { return voiceBlocked; },
       rearm: function () { voiceBlocked = false; },
       audio: function () { return voiceAudio; }
     };`
  );
  const loads = [];
  const api = factory(
    () => options.enabled !== false,
    (line, manifest, root) => (manifest && manifest.files[line] ? root + manifest.files[line] : ""),
    options.manifest === undefined
      ? { files: { "line A": "jf_tebukuro/01-a.ogg", "line B": "jf_tebukuro/02-b.ogg" } }
      : options.manifest,
    "/assets/voice/ja/",
    { Audio: FakeAudio },
    (line, reason) => misses.push(reason),
    () => loads.push("load")
  );
  return { api, plays, audios, misses, loads };
}

test("playVoiceFor drives one reusable Audio element and stays silent without a clip", () => {
  /* toggled off: no element is even created, and the reason is recorded */
  const off = makeVoiceHarness({ enabled: false });
  assert.equal(off.api.play("line A"), false);
  assert.equal(off.audios.length, 0);
  assert.equal(off.plays.length, 0);
  assert.deepEqual(off.misses, ["voice-off"]);

  /* enabled: one element, the right URL, reused so lines never overlap */
  const on = makeVoiceHarness();
  assert.equal(on.api.play("line A"), true);
  assert.equal(on.api.play("line B"), true);
  assert.equal(on.audios.length, 1, "audio elements are reused so lines never overlap");
  assert.deepEqual(on.plays, ["/assets/voice/ja/jf_tebukuro/01-a.ogg", "/assets/voice/ja/jf_tebukuro/02-b.ogg"]);

  /* unknown line: silent, nothing played, and why is recorded */
  const before = on.plays.length;
  assert.equal(on.api.play("a line nobody rendered"), false);
  assert.equal(on.plays.length, before);
  assert.deepEqual(on.misses, ["not-in-pack"]);

  /* no manifest yet: request it instead of failing forever */
  const early = makeVoiceHarness({ manifest: null });
  assert.equal(early.api.play("line A"), false);
  assert.deepEqual(early.misses, ["manifest-not-loaded"]);
  assert.deepEqual(early.loads, ["load"], "the first line should trigger the manifest fetch");
});

test("interrupting a clip is not treated as a refusal", async () => {
  const classify = new Function(`return (${extractFunctionBody("voiceBlockedReason")});`)();
  assert.equal(
    classify(Object.assign(new Error("The play() request was interrupted by a new load request."), { name: "AbortError" })),
    "",
    "a superseded clip is not a refusal"
  );
  assert.equal(classify(Object.assign(new Error("blocked"), { name: "NotAllowedError" })), "policy");
  assert.equal(classify(new Error("play() failed because the user didn't interact with the document first")), "policy");
  assert.equal(classify(new Error("some decoding hiccup")), "", "an unknown error is not proof of a refusal");

  /* Replacing .src while play() is pending rejects with AbortError; mistaking it
     for a policy block silences the mascot until the next click, which is exactly
     what a live test caught. */
  const aborted = makeVoiceHarness({ aborts: true });
  assert.equal(aborted.api.play("line A"), true);
  await Promise.resolve();
  await Promise.resolve();
  assert.equal(aborted.api.blocked(), false, "an interrupted clip must not disarm playback");
  assert.deepEqual(aborted.misses, []);
});

test("a refused play() promise disarms playback until the next gesture", async () => {
  const refused = makeVoiceHarness({ refuses: true });
  assert.equal(refused.api.play("line A"), true);
  assert.equal(refused.api.blocked(), false, "the rejection is asynchronous");
  await Promise.resolve();
  await Promise.resolve();
  assert.equal(refused.api.blocked(), true, "an autoplay refusal disarms playback instead of spamming rejections");
  assert.deepEqual(refused.misses, ["autoplay-refused"]);
  assert.equal(refused.api.play("line A"), false, "no further attempts while blocked");
  assert.deepEqual(refused.misses, ["autoplay-refused", "autoplay-blocked"]);

  refused.api.rearm();
  assert.equal(refused.api.play("line A"), true, "a user gesture re-arms playback");
  assert.equal(refused.plays.length, 2);
});

test("a synchronous autoplay failure is swallowed and disarms further attempts", () => {
  const thrown = makeVoiceHarness({ throws: true });
  assert.equal(thrown.api.play("line A"), false);
  assert.equal(thrown.api.blocked(), true);
  assert.equal(thrown.api.play("line B"), false);
  assert.deepEqual(thrown.plays, ["/assets/voice/ja/jf_tebukuro/01-a.ogg"]);
});

test("the theme install copies the whole voice tree", { skip: !packBuilt }, () => {
  const fake = path.join(rootDir, ".voice-preview", "tmp", "theme-fixture");
  const { writes } = planWrites(fake, true);
  const rels = writes.map((write) => write.rel.split(path.sep).join("/"));
  assert.ok(rels.includes("node_modules/@deepseek-ai/dsh-web-frontend/dist/assets/voice/ja/manifest.json"));
  const clips = rels.filter((rel) => rel.endsWith(".ogg"));
  assert.equal(clips.length, Object.keys(manifest.files).length);
});
